services:
  socket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8788:8788"
      - "49484:8788"
    environment:
      NODE_ENV: development
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    command: >
      sh -c "node ./dist/main.js >> /logs/socket-log.txt 2>&1"
